title = "MTProtoPy Configuration"

[server]
# Listening port for incoming connections
port = 5443
# If you have a domain name you can insert below so that share urls (tg://..) include a domain name
# otherwise leave blank and your server's public IP will be inserted
domain = "MTPROTO_SUBDOMAIN"


[mtproto]
# Server Name Indication that is inserted in TLS HelloClient packets
# if you're running this behind Caddy, this is the factor Caddy decides on where to reverse proxy the data
sni = "MTPROTO_SUBDOMAIN"
# Tag for advertising, obtainable from @MTProxybot
#ad_tag = "3c09c680b76ee91a4c25ad51f742267d"
# Enable proxying bad clients to some host
mask = true
# The next host to forward bad clients
mask_host = "MTPROTO_SUBDOMAIN"
# The next host's port to forward bad clients
mask_port = 443


[proxy]
# Configure the proxy and share urls with the assumption of running behind Caddy
caddy_reverse_proxy = true
# Accept incoming connections only with proxy protocol v1/v2, useful for nginx and haproxy
proxy_protocol = false
# Listen address for IPv4
listen_addr_ipv4 = "0.0.0.0"
# Listen address for IPv6
listen_addr_ipv6 = "::"
# Listen unix socket
listen_unix_sock = ""
# Prefer IPv6 connections
prefer_ipv6 = true
# Use middle proxy, necessary to show ad
use_middle_proxy = false
# Disables tg->client traffic re-encryption, faster but less secure
fast_mode = false


[metrics]
enabled = false
# prometheus exporter listen port, use some random port here
metrics_port = 0
# prometheus listen addr ipv4
metrics_listen_addr_ipv4 = "0.0.0.0"
# prometheus listen addr ipv6
metrics_listen_addr_ipv6 = "0"
# prometheus scrapers whitelist
metrics_whitelist = ["127.0.0.1", "::1"]
# export proxy link to prometheus
metrics_export_links = false
# default prefix for metrics
metrics_prefix = "mtprotopy_"
